export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_RESET = 'CART_RESET';

export const WHITELIST_ADD_ITEM = 'WHITELIST_ADD_ITEM';
export const WHITELIST_REMOVE_ITEM = 'WHITELIST_REMOVE_ITEM';

export const USER_SHIPPING_ADDRESS = 'USER_SHIPPING_ADDRESS';
export const CART_PAYMENT_METHOD = 'CART_PAYMENT_METHOD';
export const RESET_PAYMENT_METHOD = 'RESET_PAYMENT_METHOD';
